typedef struct no *Lista;
Lista cria_lista();
int lista_vazia(Lista lst);
int insere_final(Lista *lst, int elem);
int remove_inicio(Lista *lst, int *elem);
int insere_inicio(Lista *lst, int elem);
void imprime(Lista lst);
int tamanho(Lista lst);
int maior(Lista lst);
int remove_pares(Lista *lst);