typedef struct no * Lista;
Lista cria_lista();
int lista_vazia(Lista lst);
int insere_ord(Lista *lst, int elem);
int remove_ord(Lista *lst, int elem);
void imprime(Lista lst);
int tamanho(Lista lst);
double media(Lista lst);
int iguais(Lista lst, Lista lst1);
int ret_impares(Lista lst);