typedef struct lista *Lista;
Lista cria_lista();
int lista_vazia(Lista lst);
int lista_cheia(Lista lst);
int insere_elem(Lista lst, int elem);
int remove_elem(Lista lst, int elem);
int remove_impares(Lista lst);
int menor(Lista lst);
int ordena_lista(Lista lst);
int tamanho(Lista lst);
int concatena(Lista lst, Lista lst1);
void imprime(Lista lst);